### ISSUE TITLE
能否不占用本机的 80 和 443 端口?

### ISSUE THREAD

**Issue by chengyiqun** [dotnetcore/FastGithub#35]
因为这个还有其他用处.

**Comment by xljiulang** [comment]
FastGithub将自身伪装为Github，以欺骗浏览器来向他请求，所以github使用的端口，FastGithub也是监听相同的端口。

**Comment by txl-glory** [comment]
可以使用docker方式部署在内网虚拟机就行了，端口自己设置即可，还是比较方便的。
```
version: '3.3'
services:
  fastgithub:
    image: registry.cn-hangzhou.aliyuncs.com/txlhub/fastgithub:1.1.7
    container_name: fastgithub
    restart: always
    network_mode: 'bridge'
    ports:
      - 53:53
      - 81:80
      - 4443:443
```
